export class UpdateEquipmentBody {
  client: string;
  equipmentDad?: string | null | undefined;
  equipment: string;
  description: string;
  patrimonyNumber?: string | null;
  costCenter: string | null;
  family: string;
  equipmentType?: string | null;
  manufacturer?: string | null;
  brand?: string | null;
  plate?: string | null;
  color?: string | null;
  chassis?: string | null;
  reindeerCode?: string | null;
  CRVNumber?: string | null;
  emissionDateCRV?: string | null;
  licensing?: string | null;
  insurancePolicy?: string | null;
  insurancePolicyExpiration?: string | null;
  CTFinameNumber?: string | null;
  recipient?: string | null;
  serialNumber?: string | null;
  model: string;
  manufacturingYear: number;
  modelYear?: number | null;
  guaranteeTime?: number | null;
  costPerHour?: number | null;
  buyDate?: Date | null;
  fiscalNumber?: string | null;
  acquisitionValue: number;
  observation?: string | null;
  equipmentStatus: string;
  images: Buffer[] | null;
  consumptionType?: string | null;
  consumptionFuel?: number | null;
  unityMeter?: string | null;
  limitUnityMeter?: string | null;
  owner?: string | null;
  fleet?: string | null;
  dataSheet?: string | null;
}
